using Conv.ORM.Connection.Enums;
using System;

namespace Conv.ORM.Repository.Entities
{
    public class EntitiesColumnAttributes: Attribute
    {
        public string Name { get; set; }
        public EDataTypes DataType { get; set; }
        public int MaxSize { get; set; }
        public bool Primary { get; set; }
        public bool AutoGenerated { get; set; }
        public bool Nullable { get; set; }
        public object Default { get; set; }
        public EntitiesColumnRelationAttributes Relation { get; set; }

    }
}
