using Conv.ORM.Connections.Enums;

namespace Conv.ORM.Connections.Classes
{
    class ColumnModelEntity
    {
        public string ColumnName { get; set; }
        public object Value { get; set; }
        public EDataTypes DataType { get; set; }
        public int MaxSize { get; set; }
        public bool Primary { get; set; }
        public bool AutoGenerated { get; set; }
        public bool Nullable { get; set; }
        public RelationColumnModelEntity Relation { get; set; }
    }
}
